config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "quizzes#index"
  resources :quizzes
  resources :categories, only: [:new, :create, :show]
  resources :images
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :quizzes
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quizzes
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    if current_user.id == 1
      @category = Category.new
    else
      redirect_to root_path
    end
  end

  def create
    Category.create(category_params)
  end

  def show
    category = Category.find(params[:id])
    gon.quizzes = category.quizzes.sample(5)
    gon.images = Image.includes(:user).sample(5)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    Image.create(image_params)
    redirect_to user_path(current_user.id)
  end

  private
  def image_params
    params.require(:image).permit(:photo).merge(user_id: current_user.id)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def index
  end

  def new
    if current_user.id == 1
      @quiz = Quiz.new
    else
      redirect_to root_path
    end
  end

  def create
    Quiz.create(quiz_params)
  end

  def show
    gon.quizzes = Quiz.includes(:user).sample(5)
    gon.images = Image.includes(:user).sample(5)
  end

  private
  def quiz_params
    params.require(:quiz).permit(:text, :correct, :uncorrect1, :uncorrect2, :uncorrect3, :category_id).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @image = Image.new
    @nickname = current_user.nickname
    @images = current_user.images.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.haml
= form_for @category do |f|
  = f.text_field :name
  = f.submit '送信'

app/views/categories/show.html.haml
= render "quizzes/quiz"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title QuizWithMyCats
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = include_gon
    = javascript_include_tag 'application'
  %body
    %header.header
      .header__title
        = link_to "QuizWithMyCats", root_path
      .header__contents
        - if user_signed_in?
          = link_to current_user.nickname, "/users/#{current_user.id}", class: "userName"
          = link_to "問題作成", new_quiz_path, class: "leftBtn"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "rightBtn"
        - else
          = link_to "新規登録", new_user_registration_path, class: "leftBtn"
          = link_to "ログイン", new_user_session_path, class: "rightBtn"
    .back-image
      = yield

app/views/quizzes/_quiz.html.haml
.contents
  .quizTitle
  .text
  %ul
    %li
      %button#correct.correct
    %li
      %button#uncorrect1.uncorrect
    %li
      %button#uncorrect2.uncorrect
    %li
      %button#uncorrect3.uncorrect
#petsImage
  = image_tag "", size: "430x430", alt: "pets"
%table
  %tr
    %th
      問題
    %td
      1
    %td
      2
    %td
      3
    %td
      4
    %td
      5
  %tr
    %th
      結果
    %td.table0
    %td.table1
    %td.table2
    %td.table3
    %td.table4

.modal
  .modal__bg
  .modal__content
    %p.replay
      もう一度あそぶ
    =link_to "トップページに戻る", root_path, class: "returnTop"

app/views/quizzes/create.html.haml
%p.create
  問題作成完了しました！
  %br
    ありがとうございます！

app/views/quizzes/index.html.haml
.contents
  ジャンルを選択して下さい
  .genre
    = link_to "全ジャンル", "/quizzes/show", class: 'ノンジャンル'
    = link_to "学問", category_path(id:1), class: '学問'
    = link_to "生活", category_path(id:2), class: '生活'
    = link_to "芸能", category_path(id:3), class: '芸能'
    = link_to "スポーツ", category_path(id:4), class: 'スポーツ'

app/views/quizzes/new.html.haml
= form_for @quiz do |f|
  = f.select :category_id, [["学問",1],["生活",2],["芸能",3],["スポーツ",4]], prompt: "ジャンルを選択してください", class: 'form genreSelect'
  = f.text_area :text, placeholder: '問題文を入力して下さい', class: 'form inputText'
  = f.text_field :correct, placeholder: '答えを記入して下さい', class: 'form inputCorrect'
  = f.text_field :uncorrect1, placeholder: '他選択肢を記入して下さい', class: 'form inputUncorrect'
  = f.text_field :uncorrect2, placeholder: '他選択肢を記入して下さい', class: 'form inputUncorrect'
  = f.text_field :uncorrect3, placeholder: '他選択肢を記入して下さい', class: 'form inputUncorrect'
  = f.submit '送信', class: 'form submitBtn'

app/views/quizzes/show.html.haml
= render "quiz"

app/views/users/show.html.haml
.userPage
  .userPets
    = @nickname + "さんの投稿画像一覧"
  .petsList
    - @images.each do |image|
      .petsPhoto
        = image_tag image.photo.url, size: "200x200", alt: "pets"
        .postDate
          = image.created_at
  .petsNew
    = form_for @image do |f|
      .input
        画像を選択する→
        = f.label :photo, class: 'input__image' do
          = icon('fa', 'image')
          = f.file_field :photo, class: 'input__image__file'
          = f.submit '送信', class: 'submit-btn'